## ingest

In [4]:
dataset_id = "google_staging"

In [5]:
!bq --location=US mk --dataset {dataset_id}

Dataset 'spry-cosine-266801:google_staging' successfully created.

In [6]:
!bq --location=US load --autodetect --skip_leading_rows=1 \
--source_format=CSV {dataset_id}.mobility_report \
'gs://covid-19-csv-jy/Global_Mobility_Report.csv'

Waiting on bqjob_r6e4ecb2160004974_00000171e69965b2_1 ... (4s) Current status: DONE

In [1]:
%%bigquery
select count(*) from google_staging.mobility_report

      f0_
0  284489

In [8]:
%%bigquery
select * from google_staging.mobility_report
limit 12

,country_region_code,country_region,sub_region_1,sub_region_2,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,AE,United Arab Emirates,None,None,2020-04-05,-61,-30,-58,-79,-57,31
1,AE,United Arab Emirates,None,None,2020-04-06,-63,-32,-58,-78,-56,30
2,AE,United Arab Emirates,None,None,2020-04-07,-63,-30,-73,-78,-55,30
3,AE,United Arab Emirates,None,None,2020-04-08,-63,-30,-74,-78,-55,30
4,AE,United Arab Emirates,None,None,2020-04-09,-64,-31,-76,-79,-55,33
5,AE,United Arab Emirates,None,None,2020-04-12,-60,-28,-74,-79,-55,30
6,AE,United Arab Emirates,None,None,2020-04-13,-62,-30,-73,-78,-55,30
7,AE,United Arab Emirates,None,None,2020-04-14,-62,-31,-74,-78,-55,30
8,AE,United Arab Emirates,None,None,2020-04-15,-63,-32,-74,-78,-56,31
9,AE,United Arab Emirates,None,None,2020-04-16,-63,-32,-74,-79,-55,34
10,AE,United Arab Emirates,None,None,2020-04-19,-62,-35,-74,-78,-54,30
11,AE,United Arab Emirates,None,None,2020-04-20,-63,-37,-74,-78,-55,30